export { default as Home } from "@/assets/images/svg/li_home.svg";
export { default as Budget } from "@/assets/images/svg/Purse.svg";
export { default as Transaction } from "@/assets/images/svg/Vector (7).svg";
export { default as User } from "@/assets/images/svg/li_user.svg";
export { default as Add } from "@/assets/images/svg/Vector (8).svg";
export { default as Close } from "@/assets/images/svg/Vector (9).svg";
export { default as HomeActive } from "@/assets/images/svg/homeactive.svg";
export { default as BudgetActive } from "@/assets/images/svg/purseactive.svg";
export { default as TransactionActive } from "@/assets/images/svg/transactionactive.svg";
export { default as UserActive } from "@/assets/images/svg/useractive.svg";
export { default as Expense } from "@/assets/images/svg/arrow-top-right-o.svg";
export { default as Income } from "@/assets/images/svg/arrow-bottom-left-o.svg";
export { default as ArrowRight } from "@/assets/images/svg/arrow-right.svg";
export { default as Clock } from "@/assets/images/svg/Vector (10).svg";
export { default as ArrowLeft } from "@/assets/images/svg/arrow-left.svg";
export { default as ArrowLeftWithOutTail } from "@/assets/images/svg/Vector (11).svg";
export { default as ExpensesEmptyData } from "@/assets/images/svg/expenses.svg";
export { default as IncomeEmptyData } from "@/assets/images/svg/income.svg";
